### ISSUE TITLE
Error handling required

### ISSUE THREAD

**Issue by tomyprs** [hexatester/sid-kemendesa#1]
when trying to find a village name that is not on the db,  code return to error, it would be better if add, error handling , thanks :)

**Comment by hexatester** [comment]
Thank you for the feedback! Fixed in patch [0.1.1](https://github.com/hexatester/sid-kemendesa/releases/tag/0.1.1).
`sid_kemendesa.search` should returning an empty list by default.

**Comment by tomyprs** [comment]
thanks again dev, good job :)
